kind: Service
apiVersion: v1
metadata:
    name: {{ template "express-nodejs-template.name" . }}
spec:
    type: NodePort
    selector:
        app: {{ template "express-nodejs-template.name" . }}
    ports:
        - port: 8080
          targetPort: 8080
